### ISSUE TITLE
Refactoring needed for compatibility with Symfony 3

### ISSUE THREAD

**Issue by wasinger** [wasinger/htmlpagedom#11]
HtmlPageDom currently does not work with Symfony 3.

- Crawler does not extend SplObjectStorage any more, so all methods relying on SplObjectStorage methods need to be refactored.

- As @stof pointed out in symfony/symfony#16058 (comment), we should think about changing the architecture of HtmlPageCrawler to not extend Crawler any more but use decoration pattern

**Comment by wasinger** [comment]
**HtmlPageDom IS compatible to symfony/dom-crawler ^3.0.1**
I didn't even test it because I was convinced that it would not work, but all phpunit tests pass... So now there's out version 1.2.3 that allows dom-crawler ^3.0.1

So no need for refactoring just to support Symfony 3.

**Comment by Geczy** [comment]
That was fast. Thanks! Hope my production app doesn't break :+1:

**Comment by digilist** [comment]
Great, thank you! :+1:

**Comment by Geczy** [comment]
Has been in production without any issues so far!
