### ISSUE TITLE
Change Youtube Tags on-the-fly

### ISSUE THREAD

**Issue by skazhikadyadya** [wasinger/htmlpagedom#15]
Hi, thank you for your work!

Can I change `<iframe src="//www.youtube.com/embed/YOUTUBE_ID" width="425" height="350"></iframe>` to `<div class="youtube-player" data-id="YOUTUBE_ID"></div>` with htmlpagedom?

**Comment by skazhikadyadya** [comment]
I try to change tags:
```
        foreach ($c->filter('iframe') as $youtube)
        {
            $youtube = HtmlPageCrawler::create($youtube);
            $url = $youtube->filter('iframe')->getAttribute('src');
            if (preg_match('%(?:youtube(?:-nocookie)?\.com/(?:[^/]+/.+/|(?:v|e(?:mbed)?)/|.*[?&]v=)|youtu\.be/)([^"&?/ ]{11})%i', $url, $match)) {
                $video_id = $match[1];
                $youtube->filter('iframe')->replaceWith('<div class="youtube-player" data-id="' . $video_id . '"></div>');
            }
        }
```

But if I try to use other than youtube video? How I can filter only iframe(s) with www.youtube.com? 

Thank you.

**Comment by wasinger** [comment]
> How I can filter only iframe(s) with www.youtube.com?

```php
$c->filter('iframe[src~="www.youtube.com"]')
```

should work, not tested.

**Comment by wasinger** [comment]
Closing because it's a question about using CSS selectors and not an issue in HtmlPageDom.
