### ISSUE TITLE
Symfony/CssSelector 4.x now requires PHP 7.1.3+

### ISSUE THREAD

**Issue by smarterdigitalltd** [wasinger/htmlpagedom#26]
Hi there!

I'm in love with this library - I use it an awful lot, but it seems a couple of weeks ago the CssSelector package v4.x now requires PHP 7.1.3.

https://packagist.org/packages/symfony/css-selector

For now, I can workaround by specifying CssSelector version 2.3 - < 4.0.0 in my project composer file.

Would it be a problem to do the same in the composer file in HTMLPageDom?

Thanks for reading (and for releasing such a great tool).

**Comment by wasinger** [comment]
I don't see the problem here - HtmlPageDom requires CssSelector >=2.3, so Composer should choose any version above this that fits to the rest of the packages in your project and your PHP version. Am I missing something?
