### ISSUE TITLE
PHP8 and libxml_disable_entity_loader() deprecated

### ISSUE THREAD

**Issue by godbout** [wasinger/htmlpagedom#35]
👀 

getting some issues with PHP8 while running https://github.com/godbout/dash-docset-builder

would you consider a PR?

**Comment by godbout** [comment]
sorry, had to publish my own version of this package on Packagist. definitely not proud of it, but it seems that it's not possible to use your own repository if you're not using a root composer.json that you have to manually create/edit first. i don't want the users of `dash-docset-builder` to have to fiddle with anything. they just require the package, and start using the tool.

if you update this package to support PHP8.0 or are ok for a PR, then i'll drop my fork. thanks!

**Comment by 91320113** [comment]
thanks @godbout

**Comment by godbout** [comment]
cool, updated. dropping my fork and closing. thanks.

**Comment by tanakahisateru** [comment]
Why is it still not released for 2.x? I'm using PHP 8 and DOMCrawler 5.x.
