### ISSUE TITLE
v2.0.2 release

### ISSUE THREAD

**Issue by s-ayers** [wasinger/htmlpagedom#42]
V2.0.1 has a depreciated function. 2.x branch checks if the libxml_disable_entity_loader call is needed.
 
Exception: Deprecated function: Function libxml_disable_entity_loader() is deprecated

v3.0.0 also checks if the libxml_disable_entity_loader call is needed, and requires php8.

I want to request a new version 2 release to resolve the deprecated function exception and allows php7.

A  drupal issue that depends on this issue.
https://www.drupal.org/project/printable/issues/3293931

**Comment by wasinger** [comment]
v2.0.2 is released
