### ISSUE TITLE
mb_convert_encoding deprecation with PHP 8.3

### ISSUE THREAD

**Issue by lee-peuker** [wasinger/htmlpagedom#46]
I have updated to php 8.3 and have an issue with this package on the latest version (3.0.1):

```
Deprecated: mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in /var/www/projects/vgl-event-worker/vendor/wa72/htmlpagedom/src/Helpers.php on line 97
```

Seems like it could be related to this https://github.com/wasinger/htmlpagedom/pull/44

Any plans or ideas how to fix this?

**Comment by wasinger** [comment]
You don't use latest master or 3.x version, I guess. Just added PHP 8.3 to the unit tests workflow and all tests do pass.

**Comment by wasinger** [comment]
Just realized that you might need to use version 2.x with PHP 8.3. Indeed, in 2.x, the mb_convert_encoding problem is still present. I'll look for it in the coming days. PRs welcome :-)

**Comment by lee-peuker** [comment]
Hm, after downgrading to 2.0.3 and upgrading again to the latest version (3.0.2) it seems to work fine. Not sure why 3.0.1 did not work before, but I guess this were issues on my machine.

Thanks for the fast answer and your awesome work <3

**Comment by wasinger** [comment]
Release v2.0.4 now fixes this issue for the 2.x branch, too.
