### ISSUE TITLE
Feature: Format HTML when saving

### ISSUE THREAD

**Issue by Lakhman** [wasinger/htmlpagedom#7]
Awesome Library! - Should be part of the Symfony components!

Would it be possible to format the HTML (tidy up) when saving, perhaps it could be another method like `$page->formatHTML()->save();` (So it tidy's the HTML code)

or does this feature already exist and I missed it?

Just an idea, I could live without it but would be nice to have with such an awesome library!

Thanks!

**Comment by wasinger** [comment]
If you use the `HtmlPage` class and call `$page->save()` as your example suggests, the output should already be nicely formatted, because `HtmlPage` sets `formatOutput = true` on it's internal `DOMDocument` object.
If you use `HtmlPageCrawler` just call  `$crawler->getDOMDocument()->formatOutput = true;` before calling `$crawler->saveHTML()`.

**Comment by Lakhman** [comment]
When I use `$page->save()`, I get something like the following:

**Example Script:**

``` php
<?php

use Wa72\HtmlPageDom\HtmlPage;
use Wa72\HtmlPageDom\HtmlPageCrawler;

// .... blah blah

$htmlContent = <<<HTML
<div class="itemType">
<p class="statements">
</p>
</div>
<div class="nameLookups">
<p>SomeText</p>
</div>
HTML;

// Create an empty page
$p = new HtmlPage();
$body = $p->getBodyNode();

// Append a new node to the body (with our $htmlContent above)
$frag = $p->getDOMDocument()->createDocumentFragment();
$frag->appendXML($htmlContent);
$body->appendChild($frag); // stuff the fragment into the original tree

// Output the HTML (does not format?)
$p->getCrawler()->getDOMDocument()->formatOutput = true;
print_r($p->getCrawler()->saveHTML());
//print_r($p->save()); // This doesn't work either?
```

**Outputs:**

```html
<!DOCTYPE html>
<html>
<head><title></title></head>
<body>
<div class="itemType">
<p class="statements">
</p>
</div>
<div class="nameLookups">
<p>Contains Nuts</p>
</div>
</body>
</html>
```

**Would something like this be possible?**
Not sure if it's possible (to be able to have a more detailed HTML tidy), e.g:

```html
<!DOCTYPE html>
<html>
    <head>
        <title></title>
    </head>
    <body>
        <div class="itemType">
            <p class="statements"></p>
        </div>
        <div class="nameLookups">
            <p>Contains Nuts</p>
        </div>
    </body>
</html>
```

Am I doing something wrong or is the formatting the best it can be? (due to limitations within PHP).

Not a major issue, I suspect we can't do anything about this, if this is the case, please feel free to close. I could live without this!

**Comment by wasinger** [comment]
I see that `DOMDocument::formatOutput()` does not work reliably and I'm working on a better formatting function.

**Comment by wasinger** [comment]
In the master branch, there are now two new methods in the `HtmlPage` class:

  - `minify()` for compressing the HTML output
  - `indent()` for nicely indented output

Those methods need to be called before `save()`.

**Comment by Lakhman** [comment]
works beautifully! thank you!
